package com.jaborzodafayzali.namoztj;
import android.Manifest;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.location.*;import android.os.*;import android.view.*;import android.widget.*;import androidx.appcompat.app.AppCompatActivity;import androidx.core.app.ActivityCompat;import androidx.core.content.ContextCompat;import com.google.android.material.card.MaterialCardView;import com.jaborzodafayzali.namoztj.prayer.*;import java.util.*;
public class MainActivity extends AppCompatActivity{
 int D(float x){return(int)(x*getResources().getDisplayMetrics().density+.5f);} TextView T(String s,float z,int c,boolean b){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);t.setTypeface(Typeface.DEFAULT,b?1:0);return t;}
 MaterialCardView C(String i,String a,String b,String type){MaterialCardView c=new MaterialCardView(this);c.setRadius(D(24));c.setCardBackgroundColor(Color.rgb(19,31,48));c.setStrokeWidth(D(1));c.setStrokeColor(Color.rgb(42,64,86));c.setOnClickListener(v->startActivity(new Intent(this,FeatureActivity.class).putExtra("type",type)));LinearLayout l=new LinearLayout(this);l.setGravity(16);l.setPadding(D(15),D(13),D(15),D(13));TextView q=T(i,27,Color.WHITE,false);q.setGravity(17);l.addView(q,new LinearLayout.LayoutParams(D(52),-1));LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.addView(T(a,17,Color.WHITE,true));x.addView(T(b,12,Color.rgb(158,175,194),false));l.addView(x,new LinearLayout.LayoutParams(0,-2,1));c.addView(l);return c;}
 protected void onCreate(Bundle b){LanguageManager.apply(this);super.onCreate(b);getWindow().setStatusBarColor(Color.rgb(7,16,28));getWindow().setNavigationBarColor(Color.rgb(7,16,28));PrayerNotificationHelper.createChannel(this);notifyPermission();locationPermission();draw();}
 void draw(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setBackgroundColor(Color.rgb(7,16,28));LinearLayout h=new LinearLayout(this);h.setOrientation(LinearLayout.VERTICAL);h.setPadding(D(20),D(18),D(20),D(8));h.addView(T("NAMOZ TJ",12,Color.rgb(103,195,170),true));h.addView(T("Твоя вера. Твоё время.",27,Color.WHITE,true));h.addView(T("📍 "+(PrayerSettings.hasLocation(this)?"Местоположение определено":"Определяем местоположение…"),13,Color.rgb(163,181,201),false));r.addView(h,new LinearLayout.LayoutParams(-1,D(108)));ScrollView s=new ScrollView(this);LinearLayout g=new LinearLayout(this);g.setOrientation(LinearLayout.VERTICAL);g.setPadding(D(16),D(5),D(16),D(24));PrayerTime n=next();MaterialCardView hero=C("🕌","Следующий намаз",n==null?"—":n.name()+"  •  "+n.time(),"prayer");hero.setCardBackgroundColor(Color.rgb(13,65,61));g.addView(hero,new LinearLayout.LayoutParams(-1,D(105)));add(g,C("📖","Коран","114 сур • арабский + тоҷикӣ","quran"));add(g,C("🕰️","Время намаза","5 молитв • уведомления","prayer"));add(g,C("🤲","Дуа","50 избранных дуа","duas"));add(g,C("📿","Тасбих","Зикр • счётчик • цели","tasbih"));add(g,C("🧭","Кибла","Направление к Каабе","qibla"));add(g,C("📅","Исламский календарь","Хиджра и даты","calendar"));add(g,C("⚙️","Настройки","Язык • расчёт • уведомления","settings"));g.addView(T("JABORZODA FAYZALI  •  Namoz TJ",11,Color.rgb(102,120,140),false),new LinearLayout.LayoutParams(-1,D(40)));s.addView(g);r.addView(s,new LinearLayout.LayoutParams(-1,0,1));setContentView(r);}
 void add(LinearLayout g,View v){g.addView(v,new LinearLayout.LayoutParams(-1,D(82)));LinearLayout.LayoutParams p=(LinearLayout.LayoutParams)v.getLayoutParams();p.bottomMargin=D(9);v.setLayoutParams(p);}
 PrayerTime next(){Calendar c=Calendar.getInstance();List<PrayerTime> a=PrayerCalculator.calculate(PrayerSettings.latitude(this),PrayerSettings.longitude(this),c,TimeZone.getDefault(),PrayerSettings.method(this),PrayerSettings.school(this));String now=new java.text.SimpleDateFormat("HH:mm",Locale.US).format(new Date());for(PrayerTime x:a)if(x.time().compareTo(now)>=0)return x;return a.isEmpty()?null:a.get(0);}
 void locationPermission(){if(ContextCompat.checkSelfPermission(this,Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED)ActivityCompat.requestPermissions(this,new String[]{Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION},4101);else locate();}
 void locate(){try{LocationManager m=(LocationManager)getSystemService(LOCATION_SERVICE);Location best=null;for(String p:new String[]{LocationManager.GPS_PROVIDER,LocationManager.NETWORK_PROVIDER})if(m.isProviderEnabled(p)){Location x=m.getLastKnownLocation(p);if(x!=null&&(best==null||x.getTime()>best.getTime()))best=x;}if(best!=null)PrayerSettings.saveLocation(this,best.getLatitude(),best.getLongitude());schedule();}catch(Exception e){}}
 void schedule(){Calendar c=Calendar.getInstance();for(PrayerTime x:PrayerCalculator.calculate(PrayerSettings.latitude(this),PrayerSettings.longitude(this),c,TimeZone.getDefault(),PrayerSettings.method(this),PrayerSettings.school(this))){String[] z=x.time().split(":");Calendar a=(Calendar)c.clone();a.set(Calendar.HOUR_OF_DAY,Integer.parseInt(z[0]));a.set(Calendar.MINUTE,Integer.parseInt(z[1]));a.set(Calendar.SECOND,0);a.set(Calendar.MILLISECOND,0);if(a.before(Calendar.getInstance()))a.add(Calendar.DAY_OF_YEAR,1);PrayerAlarmScheduler.schedule(this,a.getTimeInMillis(),x.name(),x.time());}}
 void notifyPermission(){if(Build.VERSION.SDK_INT>=33&&ContextCompat.checkSelfPermission(this,Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)ActivityCompat.requestPermissions(this,new String[]{Manifest.permission.POST_NOTIFICATIONS},7001);}
 @Override public void onRequestPermissionsResult(int r,String[]p,int[]g){super.onRequestPermissionsResult(r,p,g);if(r==4101&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED){locate();draw();}}
}